apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-fabric
  namespace: hyperledger
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example.whitematrix.org
    http:
      paths:
      - path: /peer0/org1
        backend:
          serviceName: peer0-org1
          servicePort: 7051
      - path: /orderer0
        backend:
          serviceName: orderer0
          servicePort: 7050
      - path: /ca/org1
        backend:
          serviceName: ca-org1
          servicePort: 7054
      - path: /peer0/org2
        backend:
          serviceName: peer0-org2
          servicePort: 7051
      - path: /ca/org2
        backend:
          serviceName: ca-org2
          servicePort: 7054
